# -*- coding: utf-8 -*-
"""Career RecomentationP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aee0Cct8z-LP0czTC6-myZBkBBDILKmW
"""



import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import StratifiedKFold, cross_val_score

# Global mappings
SKILL_MAP = {"Weak": 0, "Average": 1, "Strong": 2}
REVERSE_SKILL_MAP = {v: k for k, v in SKILL_MAP.items()}

CAREER_GROUPS = {
    'Data Science & AI': [
        'Data Scientist', 'Data Analyst', 'Machine Learning Engineer',
        'NLP Research Scientist', 'AI Researcher', 'Machine Learning Researcher',
        'NLP Engineer', 'Computer Vision Engineer', 'Bioinformatician', 'Geospatial Analyst'
    ],
    'Software & App Development': [
        'Web Developer', 'Mobile App Developer', 'Software Engineer',
        'Embedded Software Engineer', 'IoT Developer', 'Blockchain Engineer',
        'Distributed Systems Engineer', 'Game Developer', 'Graphics Programmer', 'VR Developer'
    ],
    'Cybersecurity & Information Security': [
        'Information Security Analyst', 'Security Analyst', 'Ethical Hacker',
        'Data Privacy Specialist', 'Digital Forensics Specialist'
    ],
    'Cloud, Database & DevOps': [
        'Cloud Solutions Architect', 'DevOps Engineer', 'Database Administrator'
    ],
    'Design, UX & Creative Tech': [
        'UX Designer', 'SEO Specialist'
    ],
    'Advanced Research & Specialized IT': [
        'Quantum Computing Researcher', 'Robotics Engineer', 'Healthcare IT Specialist'
    ]
}

CATEGORY_DESCRIPTIONS = {
    'Data Science & AI': "Focused on extracting knowledge from data and building intelligent systems that can learn and predict. This field requires strong mathematical foundations and analytical intuition.",
    'Software & App Development': "The art of building robust, scalable, and user-friendly digital solutions. This vertical emphasizes clean architecture, efficient logic, and seamless user experiences.",
    'Cybersecurity & Information Security': "Protecting the integrity of digital infrastructure. This critical domain involves threat detection, risk management, and secure system design to safeguard sensitive data.",
    'Cloud, Database & DevOps': "High-performance infrastructure management. This field focuses on system reliability, automated deployment pipelines, and managing distributed data at scale.",
    'Design, UX & Creative Tech': "Bridging the gap between human needs and technical capabilities. This domain prioritizes interaction design, visual aesthetics, and human-computer interaction (HCI) principles.",
    'Advanced Research & Specialized IT': "Pushing the boundaries of computing. This field involves cutting-edge innovation in robotics, healthcare technology, and theoretical computer science."
}

# Reverse mapping for category lookup (Use Title Case for matching)
REVERSE_CAREER_MAP = {career.title(): cat for cat, careers in CAREER_GROUPS.items() for career in careers}

DOMAIN_TO_GROUP = {
    'Artificial Intelligence': 'Data Science & AI',
    'Machine Learning': 'Data Science & AI',
    'Data Science': 'Data Science & AI',
    'Data Mining': 'Data Science & AI',
    'Natural Language Processing': 'Data Science & AI',
    'Computer Vision': 'Data Science & AI',
    'Software Development': 'Software & App Development',
    'Software Engineering': 'Software & App Development',
    'Web Development': 'Software & App Development',
    'Mobile App Development': 'Software & App Development',
    'Computer Graphics': 'Software & App Development',
    'Game Development': 'Software & App Development',
    'Blockchain Technology': 'Software & App Development',
    'Distributed Systems': 'Software & App Development',
    'Cybersecurity': 'Cybersecurity & Information Security',
    'Network Security': 'Cybersecurity & Information Security',
    'Data Privacy': 'Cybersecurity & Information Security',
    'Digital Forensics': 'Cybersecurity & Information Security',
    'Database Management': 'Cloud, Database & DevOps',
    'Cloud Computing': 'Cloud, Database & DevOps',
    'Human-Computer Interaction': 'Design, UX & Creative Tech',
    'Information Retrieval': 'Design, UX & Creative Tech',
    'Quantum Computing': 'Advanced Research & Specialized IT',
    'Biomedical Computing': 'Advanced Research & Specialized IT',
    'Bioinformatics': 'Advanced Research & Specialized IT',
    'IoT (Internet of Things)': 'Software & App Development',
    'Geographic Information Systems': 'Data Science & AI'
}

def load_and_train():

    # Load dataset
    try:
        df = pd.read_csv('cs_students.csv')
    except FileNotFoundError:
        print("Error: 'cs_students.csv' not found. Please ensure the file is in the same directory.")
        return None, None, None, None

    # Drop non-predictive columns
    cols_to_drop = ['Student ID', 'Name']
    df = df.drop(columns=[c for c in cols_to_drop if c in df.columns])

    # Categorical columns
    categorical_cols = df.select_dtypes(include=['object', 'category']).columns

    # Store LabelEncoders
    le_dict = {}

    # Manual Ordinal Encoding for Skills
    skill_cols = ['Python', 'SQL', 'Java']
    for col in skill_cols:
        if col in df.columns:
            # Map values and fill missing with 'Average'
            df[col] = df[col].map(SKILL_MAP).fillna(SKILL_MAP['Average']).astype(int)
            # Remove from categorical_cols so LabelEncoder doesn't process it
            categorical_cols = [c for c in categorical_cols if c != col]

    for column in categorical_cols:

        if column == "Future Career":
            continue

        # Check if numeric stored as string
        try:
            temp_numeric = pd.to_numeric(df[column], errors='coerce')

            if temp_numeric.notnull().mean() > 0.8:
                df[column] = temp_numeric.fillna(temp_numeric.median())
                continue
        except:
            pass

        # Encode categorical
        le = LabelEncoder()
        # Normalize: strip and lowercase for robust matching
        df[column] = df[column].astype(str).str.strip().str.lower()
        df[column] = le.fit_transform(df[column])
        le_dict[column] = le

    # Encode target
    target_le = LabelEncoder()
    # Normalize target to Title Case for consistent display
    df["Future Career"] = df["Future Career"].astype(str).str.strip().str.title()
    df["Future Career"] = target_le.fit_transform(df["Future Career"])

    # Features & target
    X = df.drop("Future Career", axis=1)
    y = df["Future Career"]

    # Train-test split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    # Train model with class balance
    model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
    model.fit(X_train, y_train)

    # Accuracy with cross-validation for more reliability
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)

    # K-Fold CV (limit folds because of small dataset and single-sample classes)
    try:
        cv_scores = cross_val_score(model, X, y, cv=3)
        print(f"Model Training Complete. Test Accuracy: {accuracy * 100:.2f}%")
        print(f"Cross-Validation Accuracy: {cv_scores.mean() * 100:.2f}% (+/- {cv_scores.std() * 100:.2f}%)")
    except:
        print(f"Model Training Complete. Test Accuracy: {accuracy * 100:.2f}%")

    return model, le_dict, target_le, X.columns

# Old main function code removed here to prevent syntax errors

def get_recommendations(user_data_dict, model, le_dict, target_le, feature_columns):
    """
    Given a raw user data dictionary, returns top 3 recommendations.
    user_data_dict should have keys matching feature_columns.
    Returns: (top_cat, top_cat_prob, top_careers, top_probs)
    """
    # 1. Convert dict to input array
    input_list = [user_data_dict[col] for col in feature_columns]
    input_array = np.array(input_list).reshape(1, -1)

    # 2. Prediction Probs
    probs = model.predict_proba(input_array)[0]

    # 3. Calculate Category Confidences
    cat_confidences = {}
    career_names_from_model_classes = target_le.inverse_transform(model.classes_)

    for i, prob in enumerate(probs):
        career_name = career_names_from_model_classes[i]
        cat_name = REVERSE_CAREER_MAP.get(career_name, "Other")
        cat_confidences[cat_name] = cat_confidences.get(cat_name, 0) + prob

    # 4. Sort categories
    sorted_cats = sorted(cat_confidences.items(), key=lambda x: x[1], reverse=True)
    top_cat, top_cat_prob = sorted_cats[0]

    # 5. Get global top 3 specific careers
    top_indices = np.argsort(probs)[-3:][::-1]
    top_careers = []
    top_probs = []

    for i in top_indices:
        class_label = model.classes_[i]
        career_name = target_le.inverse_transform([class_label])[0]
        top_careers.append(career_name)
        top_probs.append(probs[i])

    return top_cat, top_cat_prob, top_careers, top_probs

def get_recommendations_df(input_df, model, le_dict, target_le, feature_columns, raw_domain=None):
    """
    Same as get_recommendations but expects a pandas DataFrame.
    """
    # 1. Prediction Probs
    probs = model.predict_proba(input_df)[0]
    
    # 1.5 Heuristic Domain Boost
    if raw_domain:
        matched_group = DOMAIN_TO_GROUP.get(raw_domain)
        if not matched_group:
            # Fuzzy fallback
            for k, v in DOMAIN_TO_GROUP.items():
                if raw_domain.lower() in k.lower() or k.lower() in raw_domain.lower():
                    matched_group = v
                    break
        
        if matched_group:
            allowed_careers = CAREER_GROUPS.get(matched_group, [])
            for i, class_label in enumerate(model.classes_):
                career_name = target_le.inverse_transform([class_label])[0]
                if career_name in allowed_careers:
                    probs[i] *= 2.5  # Heavy 150% boost to ensure domain responsiveness

    # 2. Calculate Category Confidences
    cat_confidences = {}
    career_names_from_model_classes = target_le.inverse_transform(model.classes_)

    for i, prob in enumerate(probs):
        career_name = career_names_from_model_classes[i]
        cat_name = REVERSE_CAREER_MAP.get(career_name, "Other")
        cat_confidences[cat_name] = cat_confidences.get(cat_name, 0) + prob

    # 3. Sort categories
    sorted_cats = sorted(cat_confidences.items(), key=lambda x: x[1], reverse=True)
    top_cat, top_cat_prob = sorted_cats[0]

    # 4. Get global top 3 specific careers
    top_indices = np.argsort(probs)[-3:][::-1]
    top_careers = []
    top_probs = []

    for i in top_indices:
        class_label = model.classes_[i]
        career_name = target_le.inverse_transform([class_label])[0]
        top_careers.append(career_name)
        top_probs.append(probs[i])

    return top_cat, top_cat_prob, top_careers, top_probs

def main():

    model, le_dict, target_le, feature_columns = load_and_train()

    if model is None:
        return

    while True:

        user_data_dict = {}
        # We need to get input for each feature
        # For simplicity in CLI, we still use get_user_input which returns a reshaped array
        # but the function get_recommendations expects a dict.
        # Let's adjust get_user_input to return the dict instead.
        user_data_dict = get_user_input_dict(le_dict, feature_columns)

        top_cat, top_cat_prob, top_careers, top_probs = get_recommendations(
            user_data_dict, model, le_dict, target_le, feature_columns
        )

        print("\n" + "*" * 45)
        print(f" PRIMARY FIELD: {top_cat} ({top_cat_prob*100:.1f}% Confidence)")
        print(f" TOP 3 RECOMMENDED ROLES:")
        for idx, (career, prob) in enumerate(zip(top_careers, top_probs)):
            if prob > 0:
                if idx == 0:
                    # Highlight the first recommendation
                    print(f"  >>> {idx+1}. {career.upper()} ({prob*100:.1f}%) <<< [BEST MATCH]")
                else:
                    print(f"      {idx+1}. {career} ({prob*100:.1f}%)")
        print("*" * 45)

        print("\nWhy these fields?")
        print(f"Based on your profile, we identified your primary field as '{top_cat}'.")
        print(f"Here is a breakdown of your best career fits:")

        cont = input("\nDo you want to try another prediction? (yes/no): ").lower()

        if cont != 'yes':
            print("Thank you for using the Career Recommendation System!")
            break

def get_user_input_dict(le_dict, feature_columns):
    # This is a renamed version of the old get_user_input that returns a dict
    print("\n" + "="*30)
    print(" CAREER PREDICTION SYSTEM ")
    print("="*30)
    print("Please provide your details for recommendation:\n")

    user_data = {}
    
    # Define skill columns that should use text input (Weak/Average/Strong)
    skill_columns_list = ['Python', 'SQL', 'Java']
    
    for col in feature_columns:
        if col in skill_columns_list:
            # Ordinal skill feature
            options = list(SKILL_MAP.keys())
            print(f"\n--- {col} (Skill Level) ---")
            print(f"Levels: {', '.join(options)}")
            while True:
                choice = input(f"Enter {col} (Weak/Average/Strong): ").strip()
                # Case-insensitive match for skills
                matched_skill = next((k for k in SKILL_MAP if k.lower() == choice.lower()), None)
                if matched_skill:
                    user_data[col] = SKILL_MAP[matched_skill]
                    break
                else:
                    print("Invalid input. Please choose from: Weak, Average, Strong.")
        elif col in le_dict:
            # Categorical feature
            le = le_dict[col]
            options = sorted(list(le.classes_))

            print(f"\n--- {col} ---")
            print(f"Options: {', '.join(options)}")

            while True:
                choice = input(f"Enter {col} (or type 'search' to find options): ").strip().lower()

                if choice == 'search':
                    keyword = input("Enter keyword to search for: ").lower()
                    matches = [o for o in options if keyword in o.lower()]
                    if matches:
                        print(f"Matching options: {', '.join(matches)}")
                    else:
                        print("No matches found.")
                    continue

                # 1. Try Exact Case-Insensitive Match
                matched_option = next((o for o in options if o.lower() == choice), None)
                
                # 2. Try Space-Normalized Match (e.g., 'cyber security' -> 'cybersecurity')
                if not matched_option:
                    choice_no_space = choice.replace(" ", "")
                    matched_option = next((o for o in options if o.lower().replace(" ", "") == choice_no_space), None)
                    if matched_option:
                        print(f"Auto-selected closest match: {matched_option}")

                # 3. Try Partial Match if no exact/normalized match
                if not matched_option and len(choice) > 1:
                    partial_matches = [o for o in options if choice in o.lower()]
                    if len(partial_matches) == 1:
                        matched_option = partial_matches[0]
                        print(f"Auto-selected closest match: {matched_option}")
                    elif len(partial_matches) > 1:
                        print(f"Multiple matches found: {', '.join(partial_matches)}")
                        print("Please be more specific or type the full option.")
                        continue

                if matched_option:
                    user_data[col] = le.transform([matched_option])[0]
                    break
                else:
                    print(f"Invalid input. Please choose a valid {col}. Type 'search' if you're unsure.")
        else:
            # Numerical feature
            while True:
                try:
                    val = input(f"Enter {col} (numeric): ").strip()
                    user_data[col] = float(val)
                    break
                except ValueError:
                    print(f"Invalid input. Please enter a numeric value for {col}.")
    return user_data

# Delete the old get_user_input

if __name__ == "__main__":
    main()